package ContextFreeGrammar;

/**
 * Represents a terminal symbol in a Context-Free Grammar.
 * Terminals are the basic symbols that cannot be broken down further
 * and appear in the final strings generated by the grammar.
 * They are typically represented by lowercase letters.
 *
 * @author yenennn
 * @version 1.0
 */
public class Terminal extends Symbol {

    /**
     * Constructs a new terminal symbol with the specified name.
     *
     * @param name the name of the terminal (should be lowercase)
     */
    public Terminal(String name) {
        super(name);
    }
}
