name: GraphViz Multi-Java Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  test-graphviz:
    name: Test on Java ${{ matrix.java }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false  # Continue testing other versions even if one fails
      matrix:
        java: [8, 11, 17, 21]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'  # Eclipse Temurin (AdoptOpenJDK)
          java-version: ${{ matrix.java }}
          cache: 'maven'

      - name: Print Java info
        run: |
          java -version
          echo "JAVA_HOME=$JAVA_HOME"

      - name: Run GraphViz tests
        run: mvn test -Dtest=GraphvizEngineTest

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-java${{ matrix.java }}
          path: |
            target/surefire-reports/
            target/test-classes/

  # Optional: Test Java 24 (early access) on Linux only
  test-java-24:
    name: Test on Java 24 (EA) - Linux
    runs-on: ubuntu-latest
    continue-on-error: true  # Don't fail workflow if Java 24 fails

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 24
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '24-ea'
          cache: 'maven'

      - name: Run GraphViz tests
        run: mvn test -Dtest=GraphvizEngineTest
